//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Item_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string AboutWindow {
            get {
                return ResourceManager.GetString("AboutWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string AboutWindowClose {
            get {
                return ResourceManager.GetString("AboutWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advantages/disadvantages:.
        /// </summary>
        public static string CharacterSheetAdvantages {
            get {
                return ResourceManager.GetString("CharacterSheetAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basic Lift:.
        /// </summary>
        public static string CharacterSheetBasicLift {
            get {
                return ResourceManager.GetString("CharacterSheetBasicLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basic Move:.
        /// </summary>
        public static string CharacterSheetBasicMove {
            get {
                return ResourceManager.GetString("CharacterSheetBasicMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basic Speed:.
        /// </summary>
        public static string CharacterSheetBasicSpeed {
            get {
                return ResourceManager.GetString("CharacterSheetBasicSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dexterity:.
        /// </summary>
        public static string CharacterSheetDexterity {
            get {
                return ResourceManager.GetString("CharacterSheetDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dodge:.
        /// </summary>
        public static string CharacterSheetDodge {
            get {
                return ResourceManager.GetString("CharacterSheetDodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encumbrance:.
        /// </summary>
        public static string CharacterSheetEncumbrance {
            get {
                return ResourceManager.GetString("CharacterSheetEncumbrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Health:.
        /// </summary>
        public static string CharacterSheetHealth {
            get {
                return ResourceManager.GetString("CharacterSheetHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intelligence:.
        /// </summary>
        public static string CharacterSheetIntelligence {
            get {
                return ResourceManager.GetString("CharacterSheetIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inventory:.
        /// </summary>
        public static string CharacterSheetInventory {
            get {
                return ResourceManager.GetString("CharacterSheetInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max FP:.
        /// </summary>
        public static string CharacterSheetMaxFP {
            get {
                return ResourceManager.GetString("CharacterSheetMaxFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max HP:.
        /// </summary>
        public static string CharacterSheetMaxHP {
            get {
                return ResourceManager.GetString("CharacterSheetMaxHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move:.
        /// </summary>
        public static string CharacterSheetMove {
            get {
                return ResourceManager.GetString("CharacterSheetMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No picture.
        /// </summary>
        public static string CharacterSheetNoPicture {
            get {
                return ResourceManager.GetString("CharacterSheetNoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Perception:.
        /// </summary>
        public static string CharacterSheetPerception {
            get {
                return ResourceManager.GetString("CharacterSheetPerception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skills:.
        /// </summary>
        public static string CharacterSheetSkills {
            get {
                return ResourceManager.GetString("CharacterSheetSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strength:.
        /// </summary>
        public static string CharacterSheetStrength {
            get {
                return ResourceManager.GetString("CharacterSheetStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swing damage:.
        /// </summary>
        public static string CharacterSheetSwingDamage {
            get {
                return ResourceManager.GetString("CharacterSheetSwingDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thrust damage:.
        /// </summary>
        public static string CharacterSheetThrustDamage {
            get {
                return ResourceManager.GetString("CharacterSheetThrustDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Character points:.
        /// </summary>
        public static string CharacterSheetTotalPoints {
            get {
                return ResourceManager.GetString("CharacterSheetTotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Willpower:.
        /// </summary>
        public static string CharacterSheetWillpower {
            get {
                return ResourceManager.GetString("CharacterSheetWillpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to load file..
        /// </summary>
        public static string DialogLoadFailed {
            get {
                return ResourceManager.GetString("DialogLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description:.
        /// </summary>
        public static string EditAdvantageDescription {
            get {
                return ResourceManager.GetString("EditAdvantageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        public static string EditAdvantageName {
            get {
                return ResourceManager.GetString("EditAdvantageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Points:.
        /// </summary>
        public static string EditAdvantagePoints {
            get {
                return ResourceManager.GetString("EditAdvantagePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit advantage/disadvantage.
        /// </summary>
        public static string EditAdvantageWindow {
            get {
                return ResourceManager.GetString("EditAdvantageWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string EditAdvantageWindowCancel {
            get {
                return ResourceManager.GetString("EditAdvantageWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string EditAdvantageWindowOk {
            get {
                return ResourceManager.GetString("EditAdvantageWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description:.
        /// </summary>
        public static string EditItemDescription {
            get {
                return ResourceManager.GetString("EditItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        public static string EditItemName {
            get {
                return ResourceManager.GetString("EditItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value:.
        /// </summary>
        public static string EditItemValue {
            get {
                return ResourceManager.GetString("EditItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight:.
        /// </summary>
        public static string EditItemWeight {
            get {
                return ResourceManager.GetString("EditItemWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit item.
        /// </summary>
        public static string EditItemWindow {
            get {
                return ResourceManager.GetString("EditItemWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string EditItemWindowCancel {
            get {
                return ResourceManager.GetString("EditItemWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string EditItemWindowOk {
            get {
                return ResourceManager.GetString("EditItemWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description:.
        /// </summary>
        public static string EditSkillDescription {
            get {
                return ResourceManager.GetString("EditSkillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Difficulty:.
        /// </summary>
        public static string EditSkillDifficulty {
            get {
                return ResourceManager.GetString("EditSkillDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        public static string EditSkillName {
            get {
                return ResourceManager.GetString("EditSkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relative level:.
        /// </summary>
        public static string EditSkillRelativeLevel {
            get {
                return ResourceManager.GetString("EditSkillRelativeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistic:.
        /// </summary>
        public static string EditSkillStat {
            get {
                return ResourceManager.GetString("EditSkillStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit skill.
        /// </summary>
        public static string EditSkillWindow {
            get {
                return ResourceManager.GetString("EditSkillWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string EditSkillWindowCancel {
            get {
                return ResourceManager.GetString("EditSkillWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string EditSkillWindowOk {
            get {
                return ResourceManager.GetString("EditSkillWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extra-heavy encumbrance.
        /// </summary>
        public static string EncumbranceExtraHeavy {
            get {
                return ResourceManager.GetString("EncumbranceExtraHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heavy encumbrance.
        /// </summary>
        public static string EncumbranceHeavy {
            get {
                return ResourceManager.GetString("EncumbranceHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light encumbrance.
        /// </summary>
        public static string EncumbranceLight {
            get {
                return ResourceManager.GetString("EncumbranceLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium encumbrance.
        /// </summary>
        public static string EncumbranceMedium {
            get {
                return ResourceManager.GetString("EncumbranceMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No encumbrance.
        /// </summary>
        public static string EncumbranceNo {
            get {
                return ResourceManager.GetString("EncumbranceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add advantage/disadvantage.
        /// </summary>
        public static string MenuAddAdvantage {
            get {
                return ResourceManager.GetString("MenuAddAdvantage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add item.
        /// </summary>
        public static string MenuAddItem {
            get {
                return ResourceManager.GetString("MenuAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add skill.
        /// </summary>
        public static string MenuAddSkill {
            get {
                return ResourceManager.GetString("MenuAddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit primary stats.
        /// </summary>
        public static string MenuEditPrimaryStats {
            get {
                return ResourceManager.GetString("MenuEditPrimaryStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit secondary stats.
        /// </summary>
        public static string MenuEditSecondaryStats {
            get {
                return ResourceManager.GetString("MenuEditSecondaryStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit primary stats.
        /// </summary>
        public static string PrimaryStatsWindow {
            get {
                return ResourceManager.GetString("PrimaryStatsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string PrimaryStatsWindowCancel {
            get {
                return ResourceManager.GetString("PrimaryStatsWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string PrimaryStatsWindowOk {
            get {
                return ResourceManager.GetString("PrimaryStatsWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string RibbonAppMenuItemAbout {
            get {
                return ResourceManager.GetString("RibbonAppMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DropDice.
        /// </summary>
        public static string RibbonAppMenuItemDropDice {
            get {
                return ResourceManager.GetString("RibbonAppMenuItemDropDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        public static string RibbonAppMenuItemNew {
            get {
                return ResourceManager.GetString("RibbonAppMenuItemNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string RibbonAppMenuItemOpen {
            get {
                return ResourceManager.GetString("RibbonAppMenuItemOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quit.
        /// </summary>
        public static string RibbonAppMenuItemQuit {
            get {
                return ResourceManager.GetString("RibbonAppMenuItemQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as.
        /// </summary>
        public static string RibbonAppMenuItemSaveAs {
            get {
                return ResourceManager.GetString("RibbonAppMenuItemSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Items.
        /// </summary>
        public static string RibbonButtonAllItems {
            get {
                return ResourceManager.GetString("RibbonButtonAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attachment.
        /// </summary>
        public static string RibbonButtonAttachmentItems {
            get {
                return ResourceManager.GetString("RibbonButtonAttachmentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Char.
        /// </summary>
        public static string RibbonButtonShowCharacter {
            get {
                return ResourceManager.GetString("RibbonButtonShowCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weapon.
        /// </summary>
        public static string RibbonButtonWeaponItems {
            get {
                return ResourceManager.GetString("RibbonButtonWeaponItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advantages/disadvantages.
        /// </summary>
        public static string RibbonGroupAdvantages {
            get {
                return ResourceManager.GetString("RibbonGroupAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inventory.
        /// </summary>
        public static string RibbonGroupInventory {
            get {
                return ResourceManager.GetString("RibbonGroupInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items.
        /// </summary>
        public static string RibbonGroupItems {
            get {
                return ResourceManager.GetString("RibbonGroupItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skills.
        /// </summary>
        public static string RibbonGroupSkills {
            get {
                return ResourceManager.GetString("RibbonGroupSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        public static string RibbonGroupStats {
            get {
                return ResourceManager.GetString("RibbonGroupStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Character.
        /// </summary>
        public static string RibbonSubTabCharacter {
            get {
                return ResourceManager.GetString("RibbonSubTabCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Character sheet.
        /// </summary>
        public static string RibbonTabCharacterSheet {
            get {
                return ResourceManager.GetString("RibbonTabCharacterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Genegal.
        /// </summary>
        public static string RibbonTabGeneral {
            get {
                return ResourceManager.GetString("RibbonTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit secondary stats.
        /// </summary>
        public static string SecondaryStatsWindow {
            get {
                return ResourceManager.GetString("SecondaryStatsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string SecondaryStatsWindowCancel {
            get {
                return ResourceManager.GetString("SecondaryStatsWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string SecondaryStatsWindowOk {
            get {
                return ResourceManager.GetString("SecondaryStatsWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (unnamed character).
        /// </summary>
        public static string UnnamedCharacter {
            get {
                return ResourceManager.GetString("UnnamedCharacter", resourceCulture);
            }
        }
    }
}
