version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Item_WPF.sln --verbosity m
  #- cmd: nuget restore

build:
  project: Item_WPF.sln
  verbosity: minimal
test: off
