//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF.ItemEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmountAtribute : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        private int _id;
    	public int id 
    	{ 
    		get
    		{
    			return _id;
    		} 
    		set
    		{
    			if (_id != value)
    			{
    				_id = value;
    				OnPropertyChanged("id");
    			}
    		}
    	}
        private string _per_level;
    	public string per_level 
    	{ 
    		get
    		{
    			return _per_level;
    		} 
    		set
    		{
    			if (_per_level != value)
    			{
    				_per_level = value;
    				OnPropertyChanged("per_level");
    			}
    		}
    	}
        private string _Value;
    	public string Value 
    	{ 
    		get
    		{
    			return _Value;
    		} 
    		set
    		{
    			if (_Value != value)
    			{
    				_Value = value;
    				OnPropertyChanged("Value");
    			}
    		}
    	}
        private Nullable<int> _idAtribBonus;
    	public Nullable<int> idAtribBonus 
    	{ 
    		get
    		{
    			return _idAtribBonus;
    		} 
    		set
    		{
    			if (_idAtribBonus != value)
    			{
    				_idAtribBonus = value;
    				OnPropertyChanged("idAtribBonus");
    			}
    		}
    	}
        private Nullable<int> _idWeaponBonus;
    	public Nullable<int> idWeaponBonus 
    	{ 
    		get
    		{
    			return _idWeaponBonus;
    		} 
    		set
    		{
    			if (_idWeaponBonus != value)
    			{
    				_idWeaponBonus = value;
    				OnPropertyChanged("idWeaponBonus");
    			}
    		}
    	}
    
        private attribute_bonus _attribute_bonus;
            public virtual attribute_bonus attribute_bonus
            {
                get { return _attribute_bonus; }
                set
                { if(_attribute_bonus != value)
                    {    _attribute_bonus = value;    OnPropertyChanged("attribute_bonus");   }
                }
            } 
        private weapon_bonus _weapon_bonus;
            public virtual weapon_bonus weapon_bonus
            {
                get { return _weapon_bonus; }
                set
                { if(_weapon_bonus != value)
                    {    _weapon_bonus = value;    OnPropertyChanged("weapon_bonus");   }
                }
            } 
    }
}
