//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF.ItemEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeBonu : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        private int _idAdvantage;
    	public int idAdvantage 
    	{ 
    		get
    		{
    			return _idAdvantage;
    		} 
    		set
    		{
    			if (_idAdvantage != value)
    			{
    				_idAdvantage = value;
    				OnPropertyChanged("idAdvantage");
    			}
    		}
    	}
        private Nullable<int> _idAttribute;
    	public Nullable<int> idAttribute 
    	{ 
    		get
    		{
    			return _idAttribute;
    		} 
    		set
    		{
    			if (_idAttribute != value)
    			{
    				_idAttribute = value;
    				OnPropertyChanged("idAttribute");
    			}
    		}
    	}
        private Nullable<int> _amount;
    	public Nullable<int> amount 
    	{ 
    		get
    		{
    			return _amount;
    		} 
    		set
    		{
    			if (_amount != value)
    			{
    				_amount = value;
    				OnPropertyChanged("amount");
    			}
    		}
    	}
    
        private Advantage _Advantage;
            public virtual Advantage Advantage
            {
                get { return _Advantage; }
                set
                { if(_Advantage != value)
                    {    _Advantage = value;    OnPropertyChanged("Advantage");   }
                }
            } 
        private Attribute _Attribute;
            public virtual Attribute Attribute
            {
                get { return _Attribute; }
                set
                { if(_Attribute != value)
                    {    _Attribute = value;    OnPropertyChanged("Attribute");   }
                }
            } 
    }
}
