//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF.ItemEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusAttribute : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        private int _id;
    	public int id 
    	{ 
    		get
    		{
    			return _id;
    		} 
    		set
    		{
    			if (_id != value)
    			{
    				_id = value;
    				OnPropertyChanged("id");
    			}
    		}
    	}
        private string _limitation;
    	public string limitation 
    	{ 
    		get
    		{
    			return _limitation;
    		} 
    		set
    		{
    			if (_limitation != value)
    			{
    				_limitation = value;
    				OnPropertyChanged("limitation");
    			}
    		}
    	}
        private string _Value;
    	public string Value 
    	{ 
    		get
    		{
    			return _Value;
    		} 
    		set
    		{
    			if (_Value != value)
    			{
    				_Value = value;
    				OnPropertyChanged("Value");
    			}
    		}
    	}
        private Nullable<int> _idAtribBonus;
    	public Nullable<int> idAtribBonus 
    	{ 
    		get
    		{
    			return _idAtribBonus;
    		} 
    		set
    		{
    			if (_idAtribBonus != value)
    			{
    				_idAtribBonus = value;
    				OnPropertyChanged("idAtribBonus");
    			}
    		}
    	}
    
        private attribute_bonus _attribute_bonus;
            public virtual attribute_bonus attribute_bonus
            {
                get { return _attribute_bonus; }
                set
                { if(_attribute_bonus != value)
                    {    _attribute_bonus = value;    OnPropertyChanged("attribute_bonus");   }
                }
            } 
    }
}
