//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF.ItemEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class categories1 : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categories1()
        {
            this.category1 = new HashSet<category1>();
        }
    
        private string _PrimaryKey;
    	public string PrimaryKey 
    	{ 
    		get
    		{
    			return _PrimaryKey;
    		} 
    		set
    		{
    			if (_PrimaryKey != value)
    			{
    				_PrimaryKey = value;
    				OnPropertyChanged("PrimaryKey");
    			}
    		}
    	}
        private string _category;
    	public string category 
    	{ 
    		get
    		{
    			return _category;
    		} 
    		set
    		{
    			if (_category != value)
    			{
    				_category = value;
    				OnPropertyChanged("category");
    			}
    		}
    	}
        private string _FK_skill;
    	public string FK_skill 
    	{ 
    		get
    		{
    			return _FK_skill;
    		} 
    		set
    		{
    			if (_FK_skill != value)
    			{
    				_FK_skill = value;
    				OnPropertyChanged("FK_skill");
    			}
    		}
    	}
        private string _FK_technique;
    	public string FK_technique 
    	{ 
    		get
    		{
    			return _FK_technique;
    		} 
    		set
    		{
    			if (_FK_technique != value)
    			{
    				_FK_technique = value;
    				OnPropertyChanged("FK_technique");
    			}
    		}
    	}
    
        private skill1 _skill1;
            public virtual skill1 skill1
            {
                get { return _skill1; }
                set
                { if(_skill1 != value)
                    {    _skill1 = value;    OnPropertyChanged("skill1");   }
                }
            } 
        private technique _technique;
            public virtual technique technique
            {
                get { return _technique; }
                set
                { if(_technique != value)
                    {    _technique = value;    OnPropertyChanged("technique");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<category1> _category1;
            public virtual ICollection<category1> category1
            {
                get { return _category1; }
                set
                { if(_category1 != value)
                    {    _category1 = value;    OnPropertyChanged("category1");   }
                }
            } 
    }
}
