//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF.ItemEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class category1 : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        private string _PrimaryKey;
    	public string PrimaryKey 
    	{ 
    		get
    		{
    			return _PrimaryKey;
    		} 
    		set
    		{
    			if (_PrimaryKey != value)
    			{
    				_PrimaryKey = value;
    				OnPropertyChanged("PrimaryKey");
    			}
    		}
    	}
        private string _category;
    	public string category 
    	{ 
    		get
    		{
    			return _category;
    		} 
    		set
    		{
    			if (_category != value)
    			{
    				_category = value;
    				OnPropertyChanged("category");
    			}
    		}
    	}
        private string _FK_categories;
    	public string FK_categories 
    	{ 
    		get
    		{
    			return _FK_categories;
    		} 
    		set
    		{
    			if (_FK_categories != value)
    			{
    				_FK_categories = value;
    				OnPropertyChanged("FK_categories");
    			}
    		}
    	}
    
        private categories1 _categories1;
            public virtual categories1 categories1
            {
                get { return _categories1; }
                set
                { if(_categories1 != value)
                    {    _categories1 = value;    OnPropertyChanged("categories1");   }
                }
            } 
    }
}
