//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF.ItemEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Difficulty : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Difficulty()
        {
            this.GurpsSkills = new HashSet<GurpsSkill>();
        }
    
        private int _id;
    	public int id 
    	{ 
    		get
    		{
    			return _id;
    		} 
    		set
    		{
    			if (_id != value)
    			{
    				_id = value;
    				OnPropertyChanged("id");
    			}
    		}
    	}
        private string _Name;
    	public string Name 
    	{ 
    		get
    		{
    			return _Name;
    		} 
    		set
    		{
    			if (_Name != value)
    			{
    				_Name = value;
    				OnPropertyChanged("Name");
    			}
    		}
    	}
        private string _cost;
    	public string cost 
    	{ 
    		get
    		{
    			return _cost;
    		} 
    		set
    		{
    			if (_cost != value)
    			{
    				_cost = value;
    				OnPropertyChanged("cost");
    			}
    		}
    	}
        private string _baseCost;
    	public string baseCost 
    	{ 
    		get
    		{
    			return _baseCost;
    		} 
    		set
    		{
    			if (_baseCost != value)
    			{
    				_baseCost = value;
    				OnPropertyChanged("baseCost");
    			}
    		}
    	}
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<GurpsSkill> _GurpsSkills;
            public virtual ICollection<GurpsSkill> GurpsSkills
            {
                get { return _GurpsSkills; }
                set
                { if(_GurpsSkills != value)
                    {    _GurpsSkills = value;    OnPropertyChanged("GurpsSkills");   }
                }
            } 
    }
}
