//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF.ItemEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GurpsSkillCategory : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GurpsSkillCategory()
        {
            this.GurpsSkills = new HashSet<GurpsSkill>();
        }
    
        private int _id;
    	public int id 
    	{ 
    		get
    		{
    			return _id;
    		} 
    		set
    		{
    			if (_id != value)
    			{
    				_id = value;
    				OnPropertyChanged("id");
    			}
    		}
    	}
        private string _NamelCategory;
    	public string NamelCategory 
    	{ 
    		get
    		{
    			return _NamelCategory;
    		} 
    		set
    		{
    			if (_NamelCategory != value)
    			{
    				_NamelCategory = value;
    				OnPropertyChanged("NamelCategory");
    			}
    		}
    	}
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<GurpsSkill> _GurpsSkills;
            public virtual ICollection<GurpsSkill> GurpsSkills
            {
                get { return _GurpsSkills; }
                set
                { if(_GurpsSkills != value)
                    {    _GurpsSkills = value;    OnPropertyChanged("GurpsSkills");   }
                }
            } 
    }
}
