//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF.ItemEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill_list : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public skill_list()
        {
            this.skill1 = new HashSet<skill1>();
            this.skill_container = new HashSet<skill_container>();
            this.techniques = new HashSet<technique>();
        }
    
        private string _PrimaryKey;
    	public string PrimaryKey 
    	{ 
    		get
    		{
    			return _PrimaryKey;
    		} 
    		set
    		{
    			if (_PrimaryKey != value)
    			{
    				_PrimaryKey = value;
    				OnPropertyChanged("PrimaryKey");
    			}
    		}
    	}
        private string _unique_id;
    	public string unique_id 
    	{ 
    		get
    		{
    			return _unique_id;
    		} 
    		set
    		{
    			if (_unique_id != value)
    			{
    				_unique_id = value;
    				OnPropertyChanged("unique_id");
    			}
    		}
    	}
        private string _version;
    	public string version 
    	{ 
    		get
    		{
    			return _version;
    		} 
    		set
    		{
    			if (_version != value)
    			{
    				_version = value;
    				OnPropertyChanged("version");
    			}
    		}
    	}
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<skill1> _skill1;
            public virtual ICollection<skill1> skill1
            {
                get { return _skill1; }
                set
                { if(_skill1 != value)
                    {    _skill1 = value;    OnPropertyChanged("skill1");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<skill_container> _skill_container;
            public virtual ICollection<skill_container> skill_container
            {
                get { return _skill_container; }
                set
                { if(_skill_container != value)
                    {    _skill_container = value;    OnPropertyChanged("skill_container");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<technique> _techniques;
            public virtual ICollection<technique> techniques
            {
                get { return _techniques; }
                set
                { if(_techniques != value)
                    {    _techniques = value;    OnPropertyChanged("techniques");   }
                }
            } 
    }
}
