//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF.ItemEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_prereqDB : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        private int _id;
    	public int id 
    	{ 
    		get
    		{
    			return _id;
    		} 
    		set
    		{
    			if (_id != value)
    			{
    				_id = value;
    				OnPropertyChanged("id");
    			}
    		}
    	}
        private string _nameCompare;
    	public string nameCompare 
    	{ 
    		get
    		{
    			return _nameCompare;
    		} 
    		set
    		{
    			if (_nameCompare != value)
    			{
    				_nameCompare = value;
    				OnPropertyChanged("nameCompare");
    			}
    		}
    	}
        private string _name;
    	public string name 
    	{ 
    		get
    		{
    			return _name;
    		} 
    		set
    		{
    			if (_name != value)
    			{
    				_name = value;
    				OnPropertyChanged("name");
    			}
    		}
    	}
        private string _collegeCompare;
    	public string collegeCompare 
    	{ 
    		get
    		{
    			return _collegeCompare;
    		} 
    		set
    		{
    			if (_collegeCompare != value)
    			{
    				_collegeCompare = value;
    				OnPropertyChanged("collegeCompare");
    			}
    		}
    	}
        private string _college;
    	public string college 
    	{ 
    		get
    		{
    			return _college;
    		} 
    		set
    		{
    			if (_college != value)
    			{
    				_college = value;
    				OnPropertyChanged("college");
    			}
    		}
    	}
        private string _college_countCompare;
    	public string college_countCompare 
    	{ 
    		get
    		{
    			return _college_countCompare;
    		} 
    		set
    		{
    			if (_college_countCompare != value)
    			{
    				_college_countCompare = value;
    				OnPropertyChanged("college_countCompare");
    			}
    		}
    	}
        private string _college_count;
    	public string college_count 
    	{ 
    		get
    		{
    			return _college_count;
    		} 
    		set
    		{
    			if (_college_count != value)
    			{
    				_college_count = value;
    				OnPropertyChanged("college_count");
    			}
    		}
    	}
        private string _quantityCompare;
    	public string quantityCompare 
    	{ 
    		get
    		{
    			return _quantityCompare;
    		} 
    		set
    		{
    			if (_quantityCompare != value)
    			{
    				_quantityCompare = value;
    				OnPropertyChanged("quantityCompare");
    			}
    		}
    	}
        private string _quantity;
    	public string quantity 
    	{ 
    		get
    		{
    			return _quantity;
    		} 
    		set
    		{
    			if (_quantity != value)
    			{
    				_quantity = value;
    				OnPropertyChanged("quantity");
    			}
    		}
    	}
        private string _anyt;
    	public string anyt 
    	{ 
    		get
    		{
    			return _anyt;
    		} 
    		set
    		{
    			if (_anyt != value)
    			{
    				_anyt = value;
    				OnPropertyChanged("anyt");
    			}
    		}
    	}
        private string _has;
    	public string has 
    	{ 
    		get
    		{
    			return _has;
    		} 
    		set
    		{
    			if (_has != value)
    			{
    				_has = value;
    				OnPropertyChanged("has");
    			}
    		}
    	}
        private Nullable<int> _idPrqlist;
    	public Nullable<int> idPrqlist 
    	{ 
    		get
    		{
    			return _idPrqlist;
    		} 
    		set
    		{
    			if (_idPrqlist != value)
    			{
    				_idPrqlist = value;
    				OnPropertyChanged("idPrqlist");
    			}
    		}
    	}
        private string _Value;
    	public string Value 
    	{ 
    		get
    		{
    			return _Value;
    		} 
    		set
    		{
    			if (_Value != value)
    			{
    				_Value = value;
    				OnPropertyChanged("Value");
    			}
    		}
    	}
    
        private prereq_listDB _prereq_listDB;
            public virtual prereq_listDB prereq_listDB
            {
                get { return _prereq_listDB; }
                set
                { if(_prereq_listDB != value)
                    {    _prereq_listDB = value;    OnPropertyChanged("prereq_listDB");   }
                }
            } 
    }
}
