//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class advantage_prereq : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public advantage_prereq()
        {
            this.levels = new HashSet<level>();
            this.name1 = new HashSet<name1>();
            this.notes = new HashSet<note>();
        }
    
        private string _PrimaryKey;
    	public string PrimaryKey 
    	{ 
    		get
    		{
    			return _PrimaryKey;
    		} 
    		set
    		{
    			if (_PrimaryKey != value)
    			{
    				_PrimaryKey = value;
    				OnPropertyChanged("PrimaryKey");
    			}
    		}
    	}
        private string _has;
    	public string has 
    	{ 
    		get
    		{
    			return _has;
    		} 
    		set
    		{
    			if (_has != value)
    			{
    				_has = value;
    				OnPropertyChanged("has");
    			}
    		}
    	}
        private string _FK_prereq_list;
    	public string FK_prereq_list 
    	{ 
    		get
    		{
    			return _FK_prereq_list;
    		} 
    		set
    		{
    			if (_FK_prereq_list != value)
    			{
    				_FK_prereq_list = value;
    				OnPropertyChanged("FK_prereq_list");
    			}
    		}
    	}
    
        private prereq_list1 _prereq_list1;
            public virtual prereq_list1 prereq_list1
            {
                get { return _prereq_list1; }
                set
                { if(_prereq_list1 != value)
                    {    _prereq_list1 = value;    OnPropertyChanged("prereq_list1");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<level> _levels;
            public virtual ICollection<level> levels
            {
                get { return _levels; }
                set
                { if(_levels != value)
                    {    _levels = value;    OnPropertyChanged("levels");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<name1> _name1;
            public virtual ICollection<name1> name1
            {
                get { return _name1; }
                set
                { if(_name1 != value)
                    {    _name1 = value;    OnPropertyChanged("name1");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<note> _notes;
            public virtual ICollection<note> notes
            {
                get { return _notes; }
                set
                { if(_notes != value)
                    {    _notes = value;    OnPropertyChanged("notes");   }
                }
            } 
    }
}
