//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvantageMod : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        private int _idAdvantage;
    	public int idAdvantage 
    	{ 
    		get
    		{
    			return _idAdvantage;
    		} 
    		set
    		{
    			if (_idAdvantage != value)
    			{
    				_idAdvantage = value;
    				OnPropertyChanged("idAdvantage");
    			}
    		}
    	}
        private string _NameMods;
    	public string NameMods 
    	{ 
    		get
    		{
    			return _NameMods;
    		} 
    		set
    		{
    			if (_NameMods != value)
    			{
    				_NameMods = value;
    				OnPropertyChanged("NameMods");
    			}
    		}
    	}
        private string _CostType;
    	public string CostType 
    	{ 
    		get
    		{
    			return _CostType;
    		} 
    		set
    		{
    			if (_CostType != value)
    			{
    				_CostType = value;
    				OnPropertyChanged("CostType");
    			}
    		}
    	}
        private Nullable<int> _CostAmount;
    	public Nullable<int> CostAmount 
    	{ 
    		get
    		{
    			return _CostAmount;
    		} 
    		set
    		{
    			if (_CostAmount != value)
    			{
    				_CostAmount = value;
    				OnPropertyChanged("CostAmount");
    			}
    		}
    	}
        private string _affects;
    	public string affects 
    	{ 
    		get
    		{
    			return _affects;
    		} 
    		set
    		{
    			if (_affects != value)
    			{
    				_affects = value;
    				OnPropertyChanged("affects");
    			}
    		}
    	}
        private string _Referense;
    	public string Referense 
    	{ 
    		get
    		{
    			return _Referense;
    		} 
    		set
    		{
    			if (_Referense != value)
    			{
    				_Referense = value;
    				OnPropertyChanged("Referense");
    			}
    		}
    	}
        private string _notes;
    	public string notes 
    	{ 
    		get
    		{
    			return _notes;
    		} 
    		set
    		{
    			if (_notes != value)
    			{
    				_notes = value;
    				OnPropertyChanged("notes");
    			}
    		}
    	}
    
        private Advantage _Advantage;
            public virtual Advantage Advantage
            {
                get { return _Advantage; }
                set
                { if(_Advantage != value)
                    {    _Advantage = value;    OnPropertyChanged("Advantage");   }
                }
            } 
    }
}
