//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMMOUPGRATE
    {
        public int id { get; set; }
        public string name { get; set; }
        public string shortname { get; set; }
        public int malf { get; set; }
        public decimal AR_divX { get; set; }
        public int ACC_add { get; set; }
        public decimal ACC_x { get; set; }
        public decimal damage_x { get; set; }
        public string Dam_Type { get; set; }
        public decimal range_x12 { get; set; }
        public decimal range_x { get; set; }
        public decimal ST_x { get; set; }
        public decimal WPS_x { get; set; }
        public decimal CPS_x { get; set; }
        public int Hearing { get; set; }
        public string Ammo_Class { get; set; }
        public Nullable<decimal> min_Caliber { get; set; }
        public Nullable<decimal> Max_Calider { get; set; }
        public Nullable<decimal> DT_Min_Ammo_CAliber { get; set; }
        public string Condition_DT_Min_ammo_Cal { get; set; }
        public int hearing_table { get; set; }
        public string Upgrates { get; set; }
        public string Follow_Up { get; set; }
        public string Linked { get; set; }
    }
}
