//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class amount : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        private string _PrimaryKey;
    	public string PrimaryKey 
    	{ 
    		get
    		{
    			return _PrimaryKey;
    		} 
    		set
    		{
    			if (_PrimaryKey != value)
    			{
    				_PrimaryKey = value;
    				OnPropertyChanged("PrimaryKey");
    			}
    		}
    	}
        private string _per_level;
    	public string per_level 
    	{ 
    		get
    		{
    			return _per_level;
    		} 
    		set
    		{
    			if (_per_level != value)
    			{
    				_per_level = value;
    				OnPropertyChanged("per_level");
    			}
    		}
    	}
        private string _Text;
    	public string Text 
    	{ 
    		get
    		{
    			return _Text;
    		} 
    		set
    		{
    			if (_Text != value)
    			{
    				_Text = value;
    				OnPropertyChanged("Text");
    			}
    		}
    	}
        private string _FK_weapon_bonus;
    	public string FK_weapon_bonus 
    	{ 
    		get
    		{
    			return _FK_weapon_bonus;
    		} 
    		set
    		{
    			if (_FK_weapon_bonus != value)
    			{
    				_FK_weapon_bonus = value;
    				OnPropertyChanged("FK_weapon_bonus");
    			}
    		}
    	}
    
        private weapon_bonus _weapon_bonus;
            public virtual weapon_bonus weapon_bonus
            {
                get { return _weapon_bonus; }
                set
                { if(_weapon_bonus != value)
                    {    _weapon_bonus = value;    OnPropertyChanged("weapon_bonus");   }
                }
            } 
    }
}
