//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attachment()
        {
            this.G_AvAttachClass = new HashSet<G_AvAttachClass>();
        }
    
        public int uiIndex { get; set; }
        public string szAttName { get; set; }
        public int rAttachmentClass { get; set; }
        public string Attachmentmount { get; set; }
        public bool HiddenAttachment { get; set; }
        public Nullable<int> NoiseReduction { get; set; }
        public bool HideMuzzleFlash { get; set; }
        public Nullable<int> RangeBonus { get; set; }
        public Nullable<int> AimBonus { get; set; }
        public Nullable<int> MinRangeForAimBonus { get; set; }
        public Nullable<int> MagSizeBonus { get; set; }
        public Nullable<int> BurstSizeBonus { get; set; }
        public Nullable<int> RateOfFireBonus { get; set; }
        public Nullable<int> DamageBonus { get; set; }
        public Nullable<decimal> ScopeMagFactor { get; set; }
        public Nullable<int> HearingRangeBonus { get; set; }
        public Nullable<int> VisionRangeBonus { get; set; }
        public Nullable<int> NightVisionRangeBonus { get; set; }
        public Nullable<int> DayVisionRangeBonus { get; set; }
        public Nullable<int> CaveVisionRangeBonus { get; set; }
        public Nullable<int> BrightLightVisionRangeBonus { get; set; }
        public Nullable<int> PercentTunnelVision { get; set; }
        public Nullable<int> FlashLightRange { get; set; }
        public Nullable<int> RecoilModifier { get; set; }
        public int G_SubAttachClass { get; set; }
        public int G_AttachClass { get; set; }
        public Nullable<int> Darkness { get; set; }
        public Nullable<int> Bulk_add { get; set; }
        public bool Fix { get; set; }
        public bool Tritium { get; set; }
        public Nullable<int> ScopeMagMin { get; set; }
        public Nullable<int> ScopeMagMax { get; set; }
        public Nullable<int> AccAddmax { get; set; }
        public int id_Attachmentmount { get; set; }
        public bool ImpVisSights { get; set; }
        public bool BlockIronSight { get; set; }
        public bool Collimator { get; set; }
        public bool Reflex { get; set; }
        public bool Targetingprogram { get; set; }
        public bool Laserrangefinder { get; set; }
        public Nullable<int> LaserRFrange { get; set; }
        public Nullable<int> LaserRFAcc { get; set; }
        public Nullable<int> NightVision { get; set; }
        public bool NeedIRillumination { get; set; }
        public bool Infravision { get; set; }
        public bool IRFilter { get; set; }
        public Nullable<int> LightRange { get; set; }
        public Nullable<int> IRLigRange { get; set; }
        public Nullable<int> LaserRange { get; set; }
        public string LaserColor { get; set; }
        public Nullable<decimal> laserColorEf { get; set; }
        public Nullable<int> BatTimeWork { get; set; }
    
        public virtual Attachmentmount Attachmentmount1 { get; set; }
        public virtual G_AttachClass G_AttachClass1 { get; set; }
        public virtual G_SubAttachClass G_SubAttachClass1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_AvAttachClass> G_AvAttachClass { get; set; }
        public virtual AttachmentClass AttachmentClass { get; set; }
    }
}
