//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battery
    {
        public int id { get; set; }
        public string name { get; set; }
        public string SmolName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> CPP { get; set; }
        public Nullable<decimal> WPP { get; set; }
    }
}
