//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPLOSIVE
    {
        public int uiIndex { get; set; }
        public int ubType { get; set; }
        public int ubDamage { get; set; }
        public int ubStunDamage { get; set; }
        public int ubRadius { get; set; }
        public int ubDuration { get; set; }
        public int ubStartRadius { get; set; }
        public int ubMagSize { get; set; }
        public int usNumFragments { get; set; }
        public int ubFragType { get; set; }
        public int ubFragDamage { get; set; }
        public int ubFragRange { get; set; }
        public int ubHorizontalDegree { get; set; }
        public int ubVerticalDegree { get; set; }
        public decimal bIndoorModifier { get; set; }
        public bool fExplodeOnImpact { get; set; }
        public bool GLGrenade { get; set; }
        public bool RLGrenade { get; set; }
        public bool Mine { get; set; }
        public bool Flare { get; set; }
        public bool Directional { get; set; }
        public bool ShapedCharge { get; set; }
    
        public virtual ExplosionType ExplosionType { get; set; }
    }
}
