//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class item1Entities : DbContext
    {
        public item1Entities()
            : base("name=item1Entities")
        {
    
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMMO> AMMOes { get; set; }
        public virtual DbSet<AMMOUPGRATE> AMMOUPGRATES { get; set; }
        public virtual DbSet<ARMOUR> ARMOURs { get; set; }
        public virtual DbSet<ArmourClass> ArmourClasses { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<AttachmentClass> AttachmentClasses { get; set; }
        public virtual DbSet<Attachmentmount> Attachmentmounts { get; set; }
        public virtual DbSet<ATTACHMENTSLOT> ATTACHMENTSLOTs { get; set; }
        public virtual DbSet<AttachmentSystem> AttachmentSystems { get; set; }
        public virtual DbSet<AvailableAttachSlot> AvailableAttachSlots { get; set; }
        public virtual DbSet<Battery> Batteries { get; set; }
        public virtual DbSet<CharacterDB> CharacterDBs { get; set; }
        public virtual DbSet<Cloth> Clothes { get; set; }
        public virtual DbSet<CombineWeap> CombineWeaps { get; set; }
        public virtual DbSet<Drug> Drugs { get; set; }
        public virtual DbSet<DrugType> DrugTypes { get; set; }
        public virtual DbSet<ExplosionType> ExplosionTypes { get; set; }
        public virtual DbSet<EXPLOSIVE> EXPLOSIVEs { get; set; }
        public virtual DbSet<FOOD> FOODs { get; set; }
        public virtual DbSet<G_AttachClass> G_AttachClass { get; set; }
        public virtual DbSet<G_AvAttachClass> G_AvAttachClass { get; set; }
        public virtual DbSet<G_SubAttachClass> G_SubAttachClass { get; set; }
        public virtual DbSet<ItemClass> ItemClasses { get; set; }
        public virtual DbSet<LaserColorEf> LaserColorEfs { get; set; }
        public virtual DbSet<LBEClass> LBEClasses { get; set; }
        public virtual DbSet<LC> LCs { get; set; }
        public virtual DbSet<LOADBEARINGEQUIPMENT> LOADBEARINGEQUIPMENTs { get; set; }
        public virtual DbSet<TL> TLs { get; set; }
        public virtual DbSet<TypeOfDamage> TypeOfDamages { get; set; }
        public virtual DbSet<WeaponAttackType> WeaponAttackTypes { get; set; }
        public virtual DbSet<WeaponClass> WeaponClasses { get; set; }
        public virtual DbSet<WeaponDamage> WeaponDamages { get; set; }
        public virtual DbSet<WeaponType> WeaponTypes { get; set; }
        public virtual DbSet<ITEM> ITEMs { get; set; }
        public virtual DbSet<WEAPON> WEAPONs { get; set; }
    
        public virtual int NEW_ITEM_att(string name, Nullable<int> g_att_class, Nullable<int> g_sub_att, Nullable<int> id_att_mount)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var g_att_classParameter = g_att_class.HasValue ?
                new ObjectParameter("G_att_class", g_att_class) :
                new ObjectParameter("G_att_class", typeof(int));
    
            var g_sub_attParameter = g_sub_att.HasValue ?
                new ObjectParameter("G_sub_att", g_sub_att) :
                new ObjectParameter("G_sub_att", typeof(int));
    
            var id_att_mountParameter = id_att_mount.HasValue ?
                new ObjectParameter("id_att_mount", id_att_mount) :
                new ObjectParameter("id_att_mount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NEW_ITEM_att", nameParameter, g_att_classParameter, g_sub_attParameter, id_att_mountParameter);
        }
    
        public virtual int NEW_ITEM(string name, string class_ofItem, ObjectParameter returns)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var class_ofItemParameter = class_ofItem != null ?
                new ObjectParameter("class_ofItem", class_ofItem) :
                new ObjectParameter("class_ofItem", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NEW_ITEM", nameParameter, class_ofItemParameter, returns);
        }
    
        public virtual int NEW_ITEMWeap(string name, string class_ofItem, Nullable<int> weight, Nullable<int> sT, string bulk, Nullable<decimal> cost, string lcin, string tLin, string desc, Nullable<int> rOF, Nullable<int> recoill, Nullable<int> defACCc, Nullable<int> half_Rangee, Nullable<int> fullRangee, string damagee, Nullable<int> shotss, Nullable<bool> addinChamber, Nullable<int> timeForreload, Nullable<bool> singlereload, ObjectParameter returns)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var class_ofItemParameter = class_ofItem != null ?
                new ObjectParameter("class_ofItem", class_ofItem) :
                new ObjectParameter("class_ofItem", typeof(string));
    
            var weightParameter = weight.HasValue ?
                new ObjectParameter("Weight", weight) :
                new ObjectParameter("Weight", typeof(int));
    
            var sTParameter = sT.HasValue ?
                new ObjectParameter("ST", sT) :
                new ObjectParameter("ST", typeof(int));
    
            var bulkParameter = bulk != null ?
                new ObjectParameter("Bulk", bulk) :
                new ObjectParameter("Bulk", typeof(string));
    
            var costParameter = cost.HasValue ?
                new ObjectParameter("Cost", cost) :
                new ObjectParameter("Cost", typeof(decimal));
    
            var lcinParameter = lcin != null ?
                new ObjectParameter("Lcin", lcin) :
                new ObjectParameter("Lcin", typeof(string));
    
            var tLinParameter = tLin != null ?
                new ObjectParameter("TLin", tLin) :
                new ObjectParameter("TLin", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("Desc", desc) :
                new ObjectParameter("Desc", typeof(string));
    
            var rOFParameter = rOF.HasValue ?
                new ObjectParameter("ROF", rOF) :
                new ObjectParameter("ROF", typeof(int));
    
            var recoillParameter = recoill.HasValue ?
                new ObjectParameter("Recoill", recoill) :
                new ObjectParameter("Recoill", typeof(int));
    
            var defACCcParameter = defACCc.HasValue ?
                new ObjectParameter("DefACCc", defACCc) :
                new ObjectParameter("DefACCc", typeof(int));
    
            var half_RangeeParameter = half_Rangee.HasValue ?
                new ObjectParameter("Half_Rangee", half_Rangee) :
                new ObjectParameter("Half_Rangee", typeof(int));
    
            var fullRangeeParameter = fullRangee.HasValue ?
                new ObjectParameter("FullRangee", fullRangee) :
                new ObjectParameter("FullRangee", typeof(int));
    
            var damageeParameter = damagee != null ?
                new ObjectParameter("Damagee", damagee) :
                new ObjectParameter("Damagee", typeof(string));
    
            var shotssParameter = shotss.HasValue ?
                new ObjectParameter("Shotss", shotss) :
                new ObjectParameter("Shotss", typeof(int));
    
            var addinChamberParameter = addinChamber.HasValue ?
                new ObjectParameter("AddinChamber", addinChamber) :
                new ObjectParameter("AddinChamber", typeof(bool));
    
            var timeForreloadParameter = timeForreload.HasValue ?
                new ObjectParameter("TimeForreload", timeForreload) :
                new ObjectParameter("TimeForreload", typeof(int));
    
            var singlereloadParameter = singlereload.HasValue ?
                new ObjectParameter("singlereload", singlereload) :
                new ObjectParameter("singlereload", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NEW_ITEMWeap", nameParameter, class_ofItemParameter, weightParameter, sTParameter, bulkParameter, costParameter, lcinParameter, tLinParameter, descParameter, rOFParameter, recoillParameter, defACCcParameter, half_RangeeParameter, fullRangeeParameter, damageeParameter, shotssParameter, addinChamberParameter, timeForreloadParameter, singlereloadParameter, returns);
        }
    }
}
