//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GurpsSkill : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GurpsSkill()
        {
            this.DefaultSkills = new HashSet<DefaultSkill>();
            this.DefaultSkills1 = new HashSet<DefaultSkill>();
            this.GurpsSkill1 = new HashSet<GurpsSkill>();
            this.NeedSkills = new HashSet<NeedSkill>();
            this.NeedSkills1 = new HashSet<NeedSkill>();
            this.GurpsSkillCategories = new HashSet<GurpsSkillCategory>();
        }
    
        private int _id;
    	public int id 
    	{ 
    		get
    		{
    			return _id;
    		} 
    		set
    		{
    			if (_id != value)
    			{
    				_id = value;
    				OnPropertyChanged("id");
    			}
    		}
    	}
        private string _NameSkill;
    	public string NameSkill 
    	{ 
    		get
    		{
    			return _NameSkill;
    		} 
    		set
    		{
    			if (_NameSkill != value)
    			{
    				_NameSkill = value;
    				OnPropertyChanged("NameSkill");
    			}
    		}
    	}
        private Nullable<int> _idDifficulty;
    	public Nullable<int> idDifficulty 
    	{ 
    		get
    		{
    			return _idDifficulty;
    		} 
    		set
    		{
    			if (_idDifficulty != value)
    			{
    				_idDifficulty = value;
    				OnPropertyChanged("idDifficulty");
    			}
    		}
    	}
        private Nullable<int> _Points;
    	public Nullable<int> Points 
    	{ 
    		get
    		{
    			return _Points;
    		} 
    		set
    		{
    			if (_Points != value)
    			{
    				_Points = value;
    				OnPropertyChanged("Points");
    			}
    		}
    	}
        private string _Reference;
    	public string Reference 
    	{ 
    		get
    		{
    			return _Reference;
    		} 
    		set
    		{
    			if (_Reference != value)
    			{
    				_Reference = value;
    				OnPropertyChanged("Reference");
    			}
    		}
    	}
        private Nullable<int> _idSpecialization;
    	public Nullable<int> idSpecialization 
    	{ 
    		get
    		{
    			return _idSpecialization;
    		} 
    		set
    		{
    			if (_idSpecialization != value)
    			{
    				_idSpecialization = value;
    				OnPropertyChanged("idSpecialization");
    			}
    		}
    	}
        private Nullable<bool> _TypeSpecialization;
    	public Nullable<bool> TypeSpecialization 
    	{ 
    		get
    		{
    			return _TypeSpecialization;
    		} 
    		set
    		{
    			if (_TypeSpecialization != value)
    			{
    				_TypeSpecialization = value;
    				OnPropertyChanged("TypeSpecialization");
    			}
    		}
    	}
        private Nullable<int> _DefaultModifier;
    	public Nullable<int> DefaultModifier 
    	{ 
    		get
    		{
    			return _DefaultModifier;
    		} 
    		set
    		{
    			if (_DefaultModifier != value)
    			{
    				_DefaultModifier = value;
    				OnPropertyChanged("DefaultModifier");
    			}
    		}
    	}
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<DefaultSkill> _DefaultSkills;
            public virtual ICollection<DefaultSkill> DefaultSkills
            {
                get { return _DefaultSkills; }
                set
                { if(_DefaultSkills != value)
                    {    _DefaultSkills = value;    OnPropertyChanged("DefaultSkills");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<DefaultSkill> _DefaultSkills1;
            public virtual ICollection<DefaultSkill> DefaultSkills1
            {
                get { return _DefaultSkills1; }
                set
                { if(_DefaultSkills1 != value)
                    {    _DefaultSkills1 = value;    OnPropertyChanged("DefaultSkills1");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<GurpsSkill> _GurpsSkill1;
            public virtual ICollection<GurpsSkill> GurpsSkill1
            {
                get { return _GurpsSkill1; }
                set
                { if(_GurpsSkill1 != value)
                    {    _GurpsSkill1 = value;    OnPropertyChanged("GurpsSkill1");   }
                }
            } 
        private GurpsSkill _GurpsSkill2;
            public virtual GurpsSkill GurpsSkill2
            {
                get { return _GurpsSkill2; }
                set
                { if(_GurpsSkill2 != value)
                    {    _GurpsSkill2 = value;    OnPropertyChanged("GurpsSkill2");   }
                }
            } 
        private SkillDifficulty _SkillDifficulty;
            public virtual SkillDifficulty SkillDifficulty
            {
                get { return _SkillDifficulty; }
                set
                { if(_SkillDifficulty != value)
                    {    _SkillDifficulty = value;    OnPropertyChanged("SkillDifficulty");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<NeedSkill> _NeedSkills;
            public virtual ICollection<NeedSkill> NeedSkills
            {
                get { return _NeedSkills; }
                set
                { if(_NeedSkills != value)
                    {    _NeedSkills = value;    OnPropertyChanged("NeedSkills");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<NeedSkill> _NeedSkills1;
            public virtual ICollection<NeedSkill> NeedSkills1
            {
                get { return _NeedSkills1; }
                set
                { if(_NeedSkills1 != value)
                    {    _NeedSkills1 = value;    OnPropertyChanged("NeedSkills1");   }
                }
            } 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<GurpsSkillCategory> _GurpsSkillCategories;
            public virtual ICollection<GurpsSkillCategory> GurpsSkillCategories
            {
                get { return _GurpsSkillCategories; }
                set
                { if(_GurpsSkillCategories != value)
                    {    _GurpsSkillCategories = value;    OnPropertyChanged("GurpsSkillCategories");   }
                }
            } 
    }
}
