//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LC()
        {
            this.ITEMs = new HashSet<ITEM>();
        }
    
        private int _Id_LC;
     public int Id_LC 
     { 
      get
      {
       return _Id_LC;
      } 
      set
      {
       if(_Id_LC != value)
       {
        _Id_LC = value;
        OnPropertyChanged("Id_LC");
       }
      }
     }
     
        private string _Name_LC;
     public string Name_LC 
     { 
      get
      {
       return _Name_LC;
      } 
      set
      {
       if(_Name_LC != value)
       {
        _Name_LC = value;
        OnPropertyChanged("Name_LC");
       }
      }
     }
     
        private string _ShortDes;
     public string ShortDes 
     { 
      get
      {
       return _ShortDes;
      } 
      set
      {
       if(_ShortDes != value)
       {
        _ShortDes = value;
        OnPropertyChanged("ShortDes");
       }
      }
     }
     
        private string _Description;
     public string Description 
     { 
      get
      {
       return _Description;
      } 
      set
      {
       if(_Description != value)
       {
        _Description = value;
        OnPropertyChanged("Description");
       }
      }
     }
     
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<ITEM> _ITEMs;
                public virtual ICollection<ITEM> ITEMs
                        {
                        get
                            { return _ITEMs; } 
                        set
                        { if(_ITEMs != value)
                           {    _ITEMs = value;    OnPropertyChanged("ITEMs");   }
                            }
                         } 
    }
}
