//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeedSkill : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        private int _idSkillIn;
    	public int idSkillIn 
    	{ 
    		get
    		{
    			return _idSkillIn;
    		} 
    		set
    		{
    			if (_idSkillIn != value)
    			{
    				_idSkillIn = value;
    				OnPropertyChanged("idSkillIn");
    			}
    		}
    	}
        private int _idSkillOut;
    	public int idSkillOut 
    	{ 
    		get
    		{
    			return _idSkillOut;
    		} 
    		set
    		{
    			if (_idSkillOut != value)
    			{
    				_idSkillOut = value;
    				OnPropertyChanged("idSkillOut");
    			}
    		}
    	}
        private string _Needed;
    	public string Needed 
    	{ 
    		get
    		{
    			return _Needed;
    		} 
    		set
    		{
    			if (_Needed != value)
    			{
    				_Needed = value;
    				OnPropertyChanged("Needed");
    			}
    		}
    	}
    
        private GurpsSkill _GurpsSkill;
            public virtual GurpsSkill GurpsSkill
            {
                get { return _GurpsSkill; }
                set
                { if(_GurpsSkill != value)
                    {    _GurpsSkill = value;    OnPropertyChanged("GurpsSkill");   }
                }
            } 
        private GurpsSkill _GurpsSkill1;
            public virtual GurpsSkill GurpsSkill1
            {
                get { return _GurpsSkill1; }
                set
                { if(_GurpsSkill1 != value)
                    {    _GurpsSkill1 = value;    OnPropertyChanged("GurpsSkill1");   }
                }
            } 
    }
}
