//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillBonu : System.ComponentModel.INotifyPropertyChanged
    {
     
     #region Implement INotifyPropertyChanged
     
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
     
     protected virtual void OnPropertyChanged(string propertyName)
     {
      if (PropertyChanged != null)
      {
       PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
     }
     
     #endregion
     
        private int _idAdvantage;
    	public int idAdvantage 
    	{ 
    		get
    		{
    			return _idAdvantage;
    		} 
    		set
    		{
    			if (_idAdvantage != value)
    			{
    				_idAdvantage = value;
    				OnPropertyChanged("idAdvantage");
    			}
    		}
    	}
        private int _idSkill;
    	public int idSkill 
    	{ 
    		get
    		{
    			return _idSkill;
    		} 
    		set
    		{
    			if (_idSkill != value)
    			{
    				_idSkill = value;
    				OnPropertyChanged("idSkill");
    			}
    		}
    	}
        private string _amount;
    	public string amount 
    	{ 
    		get
    		{
    			return _amount;
    		} 
    		set
    		{
    			if (_amount != value)
    			{
    				_amount = value;
    				OnPropertyChanged("amount");
    			}
    		}
    	}
    
        private Advantage _Advantage;
            public virtual Advantage Advantage
            {
                get { return _Advantage; }
                set
                { if(_Advantage != value)
                    {    _Advantage = value;    OnPropertyChanged("Advantage");   }
                }
            } 
        private Skill _Skill;
            public virtual Skill Skill
            {
                get { return _Skill; }
                set
                { if(_Skill != value)
                    {    _Skill = value;    OnPropertyChanged("Skill");   }
                }
            } 
    }
}
